axonweb3/spark

Cargo.lock
query/Cargo.toml
storage/Cargo.toml

refactor: refactor features of sea-orm

refactor: refactor features of sea-orm

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/help.yml
.github/ISSUE_TEMPLATE/others.yml

ci: add issue templates

---

common/src/traits/tx_builder.rs
common/src/types/tx_builder.rs
common/src/utils/convert.rs
tx-builder/src/ckb/define/script.rs
tx-builder/src/ckb/delegate.rs
tx-builder/src/ckb/delegate_smt.rs
tx-builder/src/ckb/init.rs
tx-builder/src/ckb/mint.rs
tx-builder/src/ckb/reward.rs
tx-builder/src/ckb/stake.rs
tx-builder/src/ckb/stake_smt.rs
tx-builder/src/ckb/test/init.rs
tx-builder/src/ckb/test/mint.rs
tx-builder/src/ckb/test/mod.rs
tx-builder/src/ckb/test/stake.rs
tx-builder/src/ckb/utils/cell_collector.rs
tx-builder/src/ckb/utils/cell_data.rs
tx-builder/src/ckb/utils/cell_dep.rs
tx-builder/src/ckb/utils/script.rs
tx-builder/src/ckb/utils/tx.rs
tx-builder/src/ckb/withdraw.rs

Build the first stake transaction.
tx: https://pudge.explorer.nervos.org/transaction/0x1ff10b25edb23e275b9db3ad7f14a50931c069cbdd2cb80587655f4218ff6dd0
tx:
```
cell deps:
omni lock dep
secp256k1 lock dep
xudt type dep
inputs:
AT cells
CKB Cells
ouptuts:
AT cell
stake AT cell
delegate cell     // todo
withdraw AT cell  // todo
CKB cell
witness:
omni eth signature
omni eth signature
```

feat: first stake

---

Cargo.lock
common/src/traits/smt.rs
common/src/traits/tx_builder.rs
common/src/types/tx_builder.rs
common/src/utils/convert.rs
tx-builder/Cargo.toml
tx-builder/src/ckb/define/error.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/mint.rs
tx-builder/src/ckb/reward.rs
tx-builder/src/ckb/tests/mod.rs
tx-builder/src/ckb/tests/reward.rs
tx-builder/src/ckb/utils/cell_collector.rs
tx-builder/src/ckb/utils/cell_data.rs
tx-builder/src/ckb/utils/cell_dep.rs
tx-builder/src/ckb/utils/script.rs

Construct a reward receiving transaction, but the witness has not yet been filled in.

feat: reward tx

---

api/src/adapter.rs
api/src/jsonrpc/axon.rs
api/src/jsonrpc/mod.rs
api/src/jsonrpc/operation.rs
api/src/jsonrpc/query.rs
api/src/tests/mod.rs
common/src/traits/api.rs
common/src/traits/ckb_rpc_client.rs
common/src/traits/query.rs
common/src/types/api.rs
common/src/types/mod.rs
common/src/types/relation_db/transaction.rs
storage/migration/src/m20220101_000001_create_table.rs
storage/src/relation_db/mod.rs

Update API interfaces according to front-end requirements.

feat: update api module

---

common/src/utils/convert.rs
tx-builder/src/ckb/delegate.rs
tx-builder/src/ckb/stake.rs
tx-builder/src/ckb/utils/calc_amount.rs
tx-builder/src/ckb/withdraw.rs

refactor: change some spelling

---

Cargo.lock
Cargo.toml
api/src/jsonrpc/mod.rs
api/src/lib.rs
api/src/tests/mod.rs
config.toml
src/config.rs
src/main.rs
storage/src/lib.rs
storage/src/smt/mod.rs
tx-builder/src/ckb/tests/stake_smt.rs

feat: add main function

---

common/src/types/tx_builder.rs
tx-builder/src/ckb/checkpoint.rs
tx-builder/src/ckb/define/types.rs
tx-builder/src/ckb/delegate_smt.rs
tx-builder/src/ckb/helper/ckb/tx.rs
tx-builder/src/ckb/helper/rest.rs
tx-builder/src/ckb/helper/withdraw.rs
tx-builder/src/ckb/init.rs
tx-builder/src/ckb/mint.rs
tx-builder/src/ckb/reward.rs
tx-builder/src/ckb/tests/reward.rs

1. Fill in the reward tx's witness.
Note: the reward tx has not been tested yet.
2. Fix delegate smt tx.

feat: fill in the reward tx's witness

---

tx-builder/src/ckb/delegate_smt.rs
tx-builder/src/ckb/stake_smt.rs

Fill stake and delegate AT cell witness.

feat: fill stake and delegate at cell witness

---

common/src/traits/tx_builder.rs
common/src/types/tx_builder.rs
common/src/utils/convert.rs
devtools/tx-tests/src/mock/mod.rs
tx-builder/src/ckb/define/types.rs
tx-builder/src/ckb/metadata.rs

feat: fill metadata tx some data

---

Cargo.lock
common/src/types/tx_builder.rs
devtools/tx-tests/Cargo.toml
devtools/tx-tests/src/mock/mod.rs
devtools/tx-tests/src/tx/checkpoint.rs
devtools/tx-tests/src/tx/init.rs
tx-builder/src/ckb/checkpoint.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/delegate_smt.rs
tx-builder/src/ckb/helper/metadata.rs
tx-builder/src/ckb/helper/withdraw.rs
tx-builder/src/ckb/init.rs
tx-builder/src/ckb/metadata.rs
tx-builder/src/ckb/stake.rs
tx-builder/src/ckb/stake_smt.rs

- Add more test case for checkpoint tx.
- Fix bug: sort validators before building metadata cell data in init tx.

test: checkpoint tx

---

common/src/traits/tx_builder.rs
rpc-client/src/axon_client/mod.rs
tx-builder/src/ckb/define/types.rs
tx-builder/src/ckb/metadata.rs

feat: fill metadata tx witness

---

common/src/traits/tx_builder.rs
devtools/tx-tests/src/mock/mod.rs
devtools/tx-tests/src/tx/init.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/init.rs
tx-builder/src/ckb/metadata.rs

Add data for metadata tx test. And the metadata tx passed the simplest test.

test: add data for metadata tx test

---

devtools/tx-tests/README.md
devtools/tx-tests/src/tx/checkpoint.rs
devtools/tx-tests/src/tx/reward.rs
devtools/tx-tests/src/tx/stake.rs
tx-builder/src/ckb/define/error.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/init.rs
tx-builder/src/ckb/reward.rs

The reward tx passed the simplest test.

test: reward tx

---

Cargo.lock
common/Cargo.toml
common/src/traits/tx_builder.rs
common/src/types/tx_builder.rs
devtools/tx-tests/src/tx/delegate.rs
devtools/tx-tests/src/tx/delegate_smt.rs
devtools/tx-tests/src/tx/init.rs
devtools/tx-tests/src/tx/metadata.rs
devtools/tx-tests/src/tx/mint.rs
devtools/tx-tests/src/tx/stake.rs
devtools/tx-tests/src/tx/stake_smt.rs
tx-builder/src/ckb/define/error.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/define/types.rs
tx-builder/src/ckb/delegate.rs
tx-builder/src/ckb/delegate_smt.rs
tx-builder/src/ckb/helper/amount_calculator.rs
tx-builder/src/ckb/helper/delegate.rs
tx-builder/src/ckb/metadata.rs
tx-builder/src/ckb/stake.rs
tx-builder/src/ckb/stake_smt.rs

Remove total amount from delegate cell.

feat: remove total amount from delegate cell

---

common/src/traits/tx_builder.rs
common/src/types/tx_builder.rs
devtools/tx-tests/README.md
devtools/tx-tests/src/cases/case1.rs
devtools/tx-tests/src/main.rs
devtools/tx-tests/src/tx/checkpoint.rs
devtools/tx-tests/src/tx/delegate.rs
devtools/tx-tests/src/tx/delegate_smt.rs
devtools/tx-tests/src/tx/faucet.rs
devtools/tx-tests/src/tx/init.rs
devtools/tx-tests/src/tx/metadata.rs
devtools/tx-tests/src/tx/mint.rs
devtools/tx-tests/src/tx/reward.rs
devtools/tx-tests/src/tx/stake.rs
devtools/tx-tests/src/tx/stake_smt.rs
devtools/tx-tests/src/tx/withdraw.rs
tx-builder/src/ckb/define/error.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/define/types.rs
tx-builder/src/ckb/delegate.rs
tx-builder/src/ckb/faucet.rs
tx-builder/src/ckb/helper/metadata.rs
tx-builder/src/ckb/init.rs
tx-builder/src/ckb/metadata.rs
tx-builder/src/ckb/mint.rs
tx-builder/src/ckb/reward.rs

- Fix reward tx.
- Don't allow stakers delegate to themselves.
- Refactor init tx & mint tx.

fix: reward tx

---

tx-builder/src/ckb/helper/amount_calculator.rs
tx-builder/src/ckb/tests/amount.rs
tx-builder/src/ckb/tests/mod.rs
tx-builder/src/ckb/tests/omni.rs

Add unit tests for amount calculator.

test: add unit tests for amount calculator

---

tx-builder/src/ckb/metadata.rs

fix: fix no top delegator

---

devtools/tx-tests/README.md
devtools/tx-tests/src/cases/delegate.rs
devtools/tx-tests/src/cases/delegate_smt.rs
devtools/tx-tests/src/cases/stake.rs
devtools/tx-tests/src/cases/stake_smt.rs
tx-builder/src/ckb/define/scripts.rs

test: generate stakers in tests

---

devtools/tx-tests/src/cases/delegate.rs
devtools/tx-tests/src/cases/delegate_smt.rs
devtools/tx-tests/src/cases/stake.rs
devtools/tx-tests/src/cases/stake_smt.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/delegate.rs
tx-builder/src/ckb/helper/amount_calculator.rs
tx-builder/src/ckb/tests/amount.rs

Change the handling of expired records.

feat: change the handling of expired records

---

Cargo.lock
devtools/tx-tests/Cargo.toml
devtools/tx-tests/src/tx/stake_smt.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/stake_smt.rs

Add test for stake sparse merkle tree.

test: add test for stake sparse merkle tree

---

devtools/tx-tests/README.md
devtools/tx-tests/src/cases/delegate_smt.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/delegate_smt.rs

fix: delegate smt tx

---

api/src/tests/mod.rs
devtools/tx-tests/src/cases/all.rs
devtools/tx-tests/src/cases/delegate.rs
devtools/tx-tests/src/cases/delegate_smt.rs
devtools/tx-tests/src/cases/metadata.rs
devtools/tx-tests/src/cases/reward.rs
devtools/tx-tests/src/cases/stake.rs
devtools/tx-tests/src/cases/stake_smt.rs
devtools/tx-tests/src/cases/withdraw.rs
devtools/tx-tests/src/helper/misc.rs
devtools/tx-tests/src/helper/mod.rs

refactor: clear smt in tests

---

devtools/tx-tests/src/tx/init.rs
tx-builder/src/ckb/define/scripts.rs
tx-builder/src/ckb/metadata.rs

fix: quorum in init tx test

---

tx-builder/src/ckb/define/scripts.rs

Update contract deployment information.

chore: update contract deployment information
